In [4]:
import numpy as np

In [5]:
a = np.arange(4)

In [6]:
a

array([0, 1, 2, 3])

In [9]:
a[[2, -1]]

array([2, 3])

In [8]:
a[[True, False, False, True]]

array([0, 3])

In [6]:
a <= 2

array([ True,  True,  True, False])

In [7]:
a[a <= 2]

array([0, 1, 2])

In [8]:
a.mean() # среднее значение

1.5

In [9]:
a[a > a.mean()]

array([2, 3])

In [10]:
a[~(a > a.mean())]  # ~ is equal like not

array([0, 1])

In [11]:
a[(a > 0) & (a <= 2)]

array([1, 2])

In [14]:
A = np.random.randint(0, 100, (4, 4))
A

array([[97, 85, 34, 48],
       [75, 29, 24, 26],
       [61,  2,  7, 57],
       [97, 59, 90, 75]])

In [15]:
A > 50

array([[ True,  True, False, False],
       [ True, False, False, False],
       [ True, False, False,  True],
       [ True,  True,  True,  True]])

In [16]:
A[A > 50]

array([97, 85, 75, 61, 57, 97, 59, 90, 75])