In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
A.ndim  # к-во измерений

2

In [5]:
A.shape # 2x3 матрица

(2, 3)

In [6]:
A.size

6

In [8]:
B = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ]
])

In [9]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
B.ndim

3

In [11]:
B.shape

(2, 2, 3)

In [12]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [13]:
A[1]

array([4, 5, 6])

In [14]:
A[1][2]

6

In [15]:
A[1, 2]

6

In [16]:
A[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
A[:, :2]  # получаю по 2 э-та каждой строки

array([[1, 2],
       [4, 5],
       [7, 8]])

In [19]:
A[1:, 2:]

array([[6],
       [9]])

In [20]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
A[0] = np.array([0, 0, 0])

In [22]:
A

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])