In [1]:
import numpy as np
import sys

In [2]:
a = np.array([1, 2, 3, 4], dtype='int32')

In [3]:
a[[-1, 1, 3]]  # get several elements by indexes from an array

array([4, 2, 4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a.dtype

dtype('int32')

In [6]:
sys.getsizeof(a)

128

In [7]:
c = np.array([1, 2, "a", 3])

In [8]:
print(c)
c.dtype  # не float/integer, а тип данных в к-й сохраняются строки

['1' '2' 'a' '3']


dtype('<U11')

In [9]:
a = np.array([1, 2, 3, 4], dtype=float)
print(a)
a.dtype

[1. 2. 3. 4.]


dtype('float64')

In [10]:
a = np.array([1, 2, 4.2], dtype=np.int8)
a

array([1, 2, 4], dtype=int8)

In [11]:
a = np.array([1, 2, 400], dtype=np.int8) # 400 - 112 = 256(байт)
a

array([   1,    2, -112], dtype=int8)