Выполняются очень быстро, на уровне процессора

In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [7]:
a + 11

array([11, 12, 13, 14])

In [8]:
a

array([0, 1, 2, 3])

In [11]:
# in python
a = [1, 2, 3, 4]
[el + 11 for el in a]

[12, 13, 14, 15]

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([50, 51, 55, 56])
a + b

array([51, 53, 58, 60])